### PR TITLE
use chalk, yargs, y18n, yargonaut

### PR DESCRIPTION
**Pull request by jrappen**
> Fair warning, I'm not a Javascript guy.

* added `.editorconfig`
* use `chalk` and `yargs` instead of `commander` and custom function
* changed script name `test` to `lint` (cause that's what it is?)

I wasn't sure how to test this. Feedback is welcome, should I need to change anything.

### CODE REVIEW

**Comment by jrappen** [comment]
For yargs should be able to use `.locale` in combination with `.updateStrings`. Haven't found out how exactly, yet. Will update as soon as I did.

**Comment by jrappen** [comment]
@QingWei-Li Not sure whether or not `chalk` should be in `package.json`. `yargonaut` uses it.

**Comment by QingWei-Li** [comment]
@jrappen `chalk` is required if the user is using npm 2

**Comment by QingWei-Li** [comment]
@jrappen 
Thank you for your contribution.
I tried it, but it did not work for me.

```bash
➜  docsify-cli git:(master) ✗ docsify serve docs
➜  docsify-cli git:(master) ✗
```

😢

**Comment by jrappen** [comment]
feel free to revert, I'll review the yargs docs

**Comment by jrappen** [comment]
apparently I cannot put `.option` after `builder: (yargs) => return yargs`

**Pull request merged**
